print ('')
print ('            |--------------------------------------| ')
print ('            |Total de uma compra em um supermencado| ')
print ('            |--------------------------------------| ')
print ('')
print ('Informe o valor dos 6 produtos')
print ('')
a = float (input ('Entre com o primeiro valor R$: '))
print ('')
b = float (input ('Entre com o segundo  valor R$: '))
print ('')
c = float (input ('Entre com o terceiro valor R$: '))
print ('')
d = float (input ('Entre com o quarto   valor R$: '))
print ('')
e = float (input ('Entre com o quinto   valor R$: '))
print ('')
f = float (input ('Entre com o sexto    valor R$: '))
print ('')
print ('Calculando Compras')
tc = a + b + c + d + e + f
print ('')
print ('O total da compra é R$: ',tc)
print ('')
print ('FIM DO PROCESSO')
